name: test

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        wget https://github.com/coolsnowwolf/lede/archive/refs/tags/20211107.zip
        unzip 20211107.zip
        ls
